/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kz.zhanbolat.log;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.LocalDateTime;
import java.util.concurrent.ScheduledThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        ScheduledThreadPoolExecutor schedule = new ScheduledThreadPoolExecutor(Runtime.getRuntime().availableProcessors() / 2);
        schedule.scheduleAtFixedRate(() -> logger.info("Log the schedule thread execution at {}", LocalDateTime.now()), 1, 10, TimeUnit.SECONDS);
        while(true) {
            // run loop
        }
    }
}
