/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kz.zhanbolat.log;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    private static final Logger logger = LogManager.getLogger(App.class);

    public static void main(String[] args) {
        logger.info("Hello World");
        logger.error("DEBUG HELLO");
    }
}
