/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kz.zhanbolat.log;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        logger.error("Error log");
    }
}
